default_environment: dev
project_id: 019b7b5d-eb3c-78ad-b17e-9cd13fa61734

environments:
- name: dev

jobs:
- name: postgres-to-s3
  tasks:
  - tap-postgres target-s3

plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      host: ${TAP_POSTGRES_HOST}
      user: ${TAP_POSTGRES_USER}
      password: ${TAP_POSTGRES_PASSWORD}
      database: ${TAP_POSTGRES_DBNAME}
      port: 5432
      filter_schemas: [public]
    select:
    - 'public-stg_governo_gastos.*'

  loaders:
  - name: target-s3
    variant: transferwise
    pip_url: pipelinewise-target-s3
    config:
      aws_access_key_id: ${TARGET_S3_AWS_ACCESS_KEY_ID}
      aws_secret_access_key: ${TARGET_S3_AWS_SECRET_ACCESS_KEY}
      s3_bucket: ${TARGET_S3_BUCKET}
      s3_key_prefix: bronze/
      file_type: parquet
      compression: gzip
      naming_convention: "{stream}/year={year}/month={month}/day={day}/{stream}_{timestamp}.parquet"
      add_metadata_columns: true
      temp_dir: /tmp